name: RadiantCore
author: tcib_cat
version: '${project.version}'
main: me.thecatisbest.radiantcore.RadiantCore
api-version: 1.13
softdepend: [PlaceholderAPI, CMI]
commands:
  radiant:
    description: The radiant command
    usage: /radiant
